-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 16:51:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Laliga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Laliga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Laliga` DEFAULT CHARACTER SET utf8 ;
USE `Laliga` ;

-- -----------------------------------------------------
-- Table `Laliga`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`EQUIPO` (
  `id_EQUIPO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `anno_fundacion` INT NOT NULL,
  `estadio` VARCHAR(45) NOT NULL,
  `poblacion` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_EQUIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`JUGADOR` (
  `idJUGADOR` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellidol` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `nacionalidad_principal` VARCHAR(45) NOT NULL,
  `nacionalidad_secundaria` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NOT NULL,
  `equipo` INT NOT NULL,
  `dorsal` VARCHAR(45) NOT NULL,
  `valor_mercado` INT NOT NULL,
  PRIMARY KEY (`idJUGADOR`),
  INDEX `FK_equipo_idx` (`equipo` ASC) VISIBLE,
  CONSTRAINT `FK_equipo_jugador`
    FOREIGN KEY (`equipo`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`TEMPORADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`TEMPORADA` (
  `id_TEMPORADA` INT NOT NULL AUTO_INCREMENT,
  `anno` VARCHAR(9) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `ganador` INT NULL,
  PRIMARY KEY (`id_TEMPORADA`),
  INDEX `FK_ganador_idx` (`ganador` ASC) VISIBLE,
  CONSTRAINT `FK_ganador_temporada`
    FOREIGN KEY (`ganador`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`PARTIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`PARTIDO` (
  `idPARTIDO` INT NOT NULL AUTO_INCREMENT,
  `equipo_local` INT NOT NULL,
  `equipo_visitante` INT NOT NULL,
  `fecha_partido` DATETIME NOT NULL,
  `goles_local` INT NULL,
  `goles_visitante` INT NULL,
  `temporada` INT NOT NULL,
  PRIMARY KEY (`idPARTIDO`),
  INDEX `FK_equipo_local_idx` (`equipo_local` ASC) VISIBLE,
  INDEX `FK_equipo_visitante_idx` (`equipo_visitante` ASC) VISIBLE,
  INDEX `FK_temporada_idx` (`temporada` ASC) VISIBLE,
  CONSTRAINT `FK_equipo_local`
    FOREIGN KEY (`equipo_local`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_equipo_visitante`
    FOREIGN KEY (`equipo_visitante`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_temporada`
    FOREIGN KEY (`temporada`)
    REFERENCES `Laliga`.`TEMPORADA` (`id_TEMPORADA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`ESTADISTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`ESTADISTICA` (
  `id_ESTADISTICA` INT NOT NULL AUTO_INCREMENT,
  `jugador` INT NOT NULL,
  `partido` INT NOT NULL,
  `goles` INT NOT NULL,
  `asistencias` INT NOT NULL,
  `tarjetas_amarillas` INT NOT NULL,
  `tarjeta_roja` INT NOT NULL,
  `minutos_jugados` INT NOT NULL,
  PRIMARY KEY (`id_ESTADISTICA`),
  INDEX `FK_jugador_idx` (`jugador` ASC) VISIBLE,
  INDEX `FK_partido_idx` (`partido` ASC) VISIBLE,
  CONSTRAINT `FK_jugador_estadistica`
    FOREIGN KEY (`jugador`)
    REFERENCES `Laliga`.`JUGADOR` (`idJUGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_partido_estadistica`
    FOREIGN KEY (`partido`)
    REFERENCES `Laliga`.`PARTIDO` (`idPARTIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`ENTRENADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`ENTRENADOR` (
  `id_ENTRENADOR` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `equipo` INT NOT NULL,
  PRIMARY KEY (`id_ENTRENADOR`),
  INDEX `FK_equipo_idx` (`equipo` ASC) VISIBLE,
  CONSTRAINT `FK_equipo_entrenador`
    FOREIGN KEY (`equipo`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laliga`.`CLASIFICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laliga`.`CLASIFICACION` (
  `id_CLASIFICACION` INT NOT NULL AUTO_INCREMENT,
  `equipo` INT NOT NULL,
  `temporada` INT NOT NULL,
  `posicion` INT NOT NULL,
  `puntos` INT NOT NULL,
  `goles_marcados` INT NOT NULL,
  `goles_encajados` INT NOT NULL,
  PRIMARY KEY (`id_CLASIFICACION`),
  INDEX `FK_equipo_idx` (`equipo` ASC) VISIBLE,
  INDEX `FK_temporada_idx` (`temporada` ASC) VISIBLE,
  CONSTRAINT `FK_equipo_clasificacion`
    FOREIGN KEY (`equipo`)
    REFERENCES `Laliga`.`EQUIPO` (`id_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_temporada_clasificacion`
    FOREIGN KEY (`temporada`)
    REFERENCES `Laliga`.`TEMPORADA` (`id_TEMPORADA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
