/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Havana.java
 *
 * Created on 16-oct-2011, 11:38:26
 */

package di01_tarea;

import org.jdesktop.application.Action;

/**
 *
 * @author usuario
 */
public class Havana extends javax.swing.JDialog {

    /** Creates new form Havana */
    public Havana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pnlDatosContacto = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        pnlDatosReserva = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblNPersonas = new javax.swing.JLabel();
        txtNPersonas = new javax.swing.JTextField();
        chkHabitaciones = new javax.swing.JCheckBox();
        pnlTipo = new javax.swing.JPanel();
        rdoBanquete = new javax.swing.JRadioButton();
        rdoJornada = new javax.swing.JRadioButton();
        rdoCongreso = new javax.swing.JRadioButton();
        spnDias = new javax.swing.JSpinner();
        lblDias = new javax.swing.JLabel();
        spnfecha = new javax.swing.JSpinner();
        lblCocina = new javax.swing.JLabel();
        cmbCocina = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(di01_tarea.DI01_TareaApp.class).getContext().getResourceMap(Havana.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        pnlDatosContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("pnlDatosContacto.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("pnlDatosContacto.border.titleFont"), resourceMap.getColor("pnlDatosContacto.border.titleColor"))); // NOI18N
        pnlDatosContacto.setName("pnlDatosContacto"); // NOI18N

        lblNombre.setFont(resourceMap.getFont("lblNombre.font")); // NOI18N
        lblNombre.setLabelFor(txtNombre);
        lblNombre.setText(resourceMap.getString("lblNombre.text")); // NOI18N
        lblNombre.setName("lblNombre"); // NOI18N

        lblTelefono.setFont(resourceMap.getFont("lblTelefono.font")); // NOI18N
        lblTelefono.setLabelFor(txtTelefono);
        lblTelefono.setText(resourceMap.getString("lblTelefono.text")); // NOI18N
        lblTelefono.setName("lblTelefono"); // NOI18N

        txtNombre.setText(resourceMap.getString("txtNombre.text")); // NOI18N
        txtNombre.setToolTipText(resourceMap.getString("txtNombre.toolTipText")); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.setNextFocusableComponent(txtTelefono);

        txtTelefono.setText(resourceMap.getString("txtTelefono.text")); // NOI18N
        txtTelefono.setToolTipText(resourceMap.getString("txtTelefono.toolTipText")); // NOI18N
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.setNextFocusableComponent(spnfecha);

        javax.swing.GroupLayout pnlDatosContactoLayout = new javax.swing.GroupLayout(pnlDatosContacto);
        pnlDatosContacto.setLayout(pnlDatosContactoLayout);
        pnlDatosContactoLayout.setHorizontalGroup(
            pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosContactoLayout.createSequentialGroup()
                .addGroup(pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDatosContactoLayout.setVerticalGroup(
            pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosContactoLayout.createSequentialGroup()
                .addGroup(pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("pnlDatosReserva.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("pnlDatosReserva.border.titleFont"))); // NOI18N
        pnlDatosReserva.setName("pnlDatosReserva"); // NOI18N

        lblFecha.setFont(resourceMap.getFont("lblFecha.font")); // NOI18N
        lblFecha.setLabelFor(spnfecha);
        lblFecha.setText(resourceMap.getString("lblFecha.text")); // NOI18N
        lblFecha.setName("lblFecha"); // NOI18N

        lblNPersonas.setFont(resourceMap.getFont("lblNPersonas.font")); // NOI18N
        lblNPersonas.setLabelFor(txtNPersonas);
        lblNPersonas.setText(resourceMap.getString("lblNPersonas.text")); // NOI18N
        lblNPersonas.setName("lblNPersonas"); // NOI18N

        txtNPersonas.setText(resourceMap.getString("txtNPersonas.text")); // NOI18N
        txtNPersonas.setName("txtNPersonas"); // NOI18N
        txtNPersonas.setNextFocusableComponent(rdoBanquete);

        chkHabitaciones.setText(resourceMap.getString("chkHabitaciones.text")); // NOI18N
        chkHabitaciones.setEnabled(false);
        chkHabitaciones.setName("chkHabitaciones"); // NOI18N
        chkHabitaciones.setNextFocusableComponent(btnAceptar);

        pnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("pnlTipo.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("pnlTipo.border.titleFont"))); // NOI18N
        pnlTipo.setName("pnlTipo"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(di01_tarea.DI01_TareaApp.class).getContext().getActionMap(Havana.class, this);
        rdoBanquete.setAction(actionMap.get("desactivar")); // NOI18N
        grpTipo.add(rdoBanquete);
        rdoBanquete.setText(resourceMap.getString("rdoBanquete.text")); // NOI18N
        rdoBanquete.setToolTipText(resourceMap.getString("rdoBanquete.toolTipText")); // NOI18N
        rdoBanquete.setName("rdoBanquete"); // NOI18N
        rdoBanquete.setNextFocusableComponent(rdoJornada);

        rdoJornada.setAction(actionMap.get("desactivar")); // NOI18N
        grpTipo.add(rdoJornada);
        rdoJornada.setText(resourceMap.getString("rdoJornada.text")); // NOI18N
        rdoJornada.setToolTipText(resourceMap.getString("rdoJornada.toolTipText")); // NOI18N
        rdoJornada.setName("rdoJornada"); // NOI18N
        rdoJornada.setNextFocusableComponent(rdoCongreso);

        rdoCongreso.setAction(actionMap.get("activar")); // NOI18N
        grpTipo.add(rdoCongreso);
        rdoCongreso.setText(resourceMap.getString("rdoCongreso.text")); // NOI18N
        rdoCongreso.setToolTipText(resourceMap.getString("rdoCongreso.toolTipText")); // NOI18N
        rdoCongreso.setName("rdoCongreso"); // NOI18N
        rdoCongreso.setNextFocusableComponent(cmbCocina);
        rdoCongreso.setRolloverEnabled(false);
        rdoCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCongresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoLayout = new javax.swing.GroupLayout(pnlTipo);
        pnlTipo.setLayout(pnlTipoLayout);
        pnlTipoLayout.setHorizontalGroup(
            pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoBanquete)
                    .addComponent(rdoJornada)
                    .addComponent(rdoCongreso))
                .addContainerGap())
        );
        pnlTipoLayout.setVerticalGroup(
            pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoLayout.createSequentialGroup()
                .addComponent(rdoBanquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoJornada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoCongreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnDias.setEnabled(false);
        spnDias.setName("spnDias"); // NOI18N
        spnDias.setNextFocusableComponent(chkHabitaciones);
        spnDias.setVerifyInputWhenFocusTarget(false);

        lblDias.setFont(resourceMap.getFont("lblDias.font")); // NOI18N
        lblDias.setLabelFor(spnDias);
        lblDias.setText(resourceMap.getString("lblDias.text")); // NOI18N
        lblDias.setEnabled(false);
        lblDias.setName("lblDias"); // NOI18N

        spnfecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1318759860000L), new java.util.Date(1318759860000L), new java.util.Date(1449918660000L), java.util.Calendar.DAY_OF_YEAR));
        spnfecha.setName("spnfecha"); // NOI18N
        spnfecha.setNextFocusableComponent(txtNPersonas);

        lblCocina.setFont(resourceMap.getFont("lblCocina.font")); // NOI18N
        lblCocina.setLabelFor(cmbCocina);
        lblCocina.setText(resourceMap.getString("lblCocina.text")); // NOI18N
        lblCocina.setName("lblCocina"); // NOI18N

        cmbCocina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buffet libre", "Carta", "Pedir cita con el chef", "No precisa" }));
        cmbCocina.setName("cmbCocina"); // NOI18N
        cmbCocina.setNextFocusableComponent(spnDias);

        javax.swing.GroupLayout pnlDatosReservaLayout = new javax.swing.GroupLayout(pnlDatosReserva);
        pnlDatosReserva.setLayout(pnlDatosReservaLayout);
        pnlDatosReservaLayout.setHorizontalGroup(
            pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                        .addComponent(pnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDias)
                                .addGap(4, 4, 4)
                                .addComponent(spnDias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkHabitaciones))
                            .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCocina)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                        .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(spnfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNPersonas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosReservaLayout.setVerticalGroup(
            pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(5, 5, 5)
                        .addComponent(spnfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                        .addComponent(lblNPersonas)
                        .addGap(5, 5, 5)
                        .addComponent(txtNPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCocina)
                            .addComponent(cmbCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblDias)
                            .addComponent(spnDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkHabitaciones))
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );

        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.setNextFocusableComponent(btnCancelar);

        btnCancelar.setAction(actionMap.get("cerrar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCongresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoCongresoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Havana dialog = new Havana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void cerrar() {
         dispose();
    }

    @Action
    public void activar() {
        if (rdoCongreso.isSelected())
        {
            if (lblDias.isEnabled() == false)
            {
                lblDias.setEnabled(true);
            }
            if (spnDias.isEnabled() == false)
            {
                spnDias.setEnabled(true);
            }
            if (chkHabitaciones.isEnabled() == false)
            {
                chkHabitaciones.setEnabled(true);
            }
        }
        
    }

    @Action
    public void desactivar() {
        lblDias.setEnabled(false);
        spnDias.setEnabled(false);
        chkHabitaciones.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkHabitaciones;
    private javax.swing.JComboBox cmbCocina;
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCocina;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNPersonas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlDatosContacto;
    private javax.swing.JPanel pnlDatosReserva;
    private javax.swing.JPanel pnlTipo;
    private javax.swing.JRadioButton rdoBanquete;
    private javax.swing.JRadioButton rdoCongreso;
    private javax.swing.JRadioButton rdoJornada;
    private javax.swing.JSpinner spnDias;
    private javax.swing.JSpinner spnfecha;
    private javax.swing.JTextField txtNPersonas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
