/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * alarmaEditorPanel.java
 *
 * Created on 09-nov-2011, 23:34:38
 */

package RelojDigital;

/**
 *
 * @author usuario
 */
public class alarmaEditorPanel extends javax.swing.JPanel {

    /** Creates new form alarmaEditorPanel */
    public alarmaEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_AM_FM = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdo12horas = new javax.swing.JRadioButton();
        rdo24horas = new javax.swing.JRadioButton();
        txtMsg = new javax.swing.JTextField();
        chkActiva = new javax.swing.JCheckBox();
        txtHoras = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();

        jLabel1.setText("Hora");

        jLabel2.setText("Minutos");

        jLabel3.setText("Mensaje");

        btngrp_AM_FM.add(rdo12horas);
        rdo12horas.setText("12 horas");
        rdo12horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo12horasActionPerformed(evt);
            }
        });

        btngrp_AM_FM.add(rdo24horas);
        rdo24horas.setText("24 horas");
        rdo24horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo24horasActionPerformed(evt);
            }
        });

        chkActiva.setText("Activa");

        txtHoras.setText("0");

        txtMinutos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addGap(307, 307, 307)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdo24horas)
                                .addComponent(rdo12horas)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkActiva)))
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rdo12horas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo24horas)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkActiva))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdo12horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo12horasActionPerformed
        // TODO add your handling code here:
        //sldHoras.setMaximum(12);
    }//GEN-LAST:event_rdo12horasActionPerformed

    private void rdo24horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo24horasActionPerformed
        // TODO add your handling code here:
        //sldHoras.setMaximum(24);
    }//GEN-LAST:event_rdo24horasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrp_AM_FM;
    public javax.swing.JCheckBox chkActiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JRadioButton rdo12horas;
    public javax.swing.JRadioButton rdo24horas;
    public javax.swing.JTextField txtHoras;
    public javax.swing.JTextField txtMinutos;
    public javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables

}
